#!/bin/bash
#SBATCH --job-name=med3d_inspect
#SBATCH --time=01:00:00
#SBATCH --partition=gpu
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --output=/home/remote/%u/logs/%x_%j.out
#SBATCH --error=/home/remote/%u/logs/%x_%j.err

# 1. Load the cluster's Conda module
module load miniforge3
nvcc --version

# 1. Complete isolation
export PYTHONNOUSERSITE=1
export PYTHONPATH=""

# 2. Force library priority
export LD_LIBRARY_PATH="/scratch/user/jlateef/med3d/lib:$LD_LIBRARY_PATH"

# 4. Use the full path to your python (as you did before)
#/scratch/user/jlateef/llava/bin/pip install -r /scratch/group/CX000019_DS1/vlm-brain-mri/Med3DVLM/requirements.txt 
/scratch/user/jlateef/med3d/bin/python /scratch/group/CX000019_DS1/vlm-brain-mri/QA-BrainTumor-VLM-UCSF-/finetune_scripts/model_inspect.py
echo "------------------------------------------------------------"
echo "Job finished at $(date)"