#!/bin/bash
#SBATCH --job-name=Prima_test
#SBATCH --time=6:00:00
#SBATCH --partition=gpu
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --output=/home/remote/%u/logs/%x_%j.out
#SBATCH --error=/home/remote/%u/logs/%x_%j.err

# 1. Load the cluster's Conda module
module load miniforge3

# 2. Prevent "Ghost" package leakage (The root of our earlier problems)
export PYTHONNOUSERSITE=1
unset PYTHONPATH

source ~/prima/bin/activate



cd /scratch/group/CX000019_DS1/vlm-brain-mri/Prima

echo "------------------------------------------------------------"
echo "Job ID:        $SLURM_JOB_ID"
echo "User:          $USER"
echo "------------------------------------------------------------"

# 4. RUN (Using the direct path to bypass activation bugs)
python end-to-end_inference_pipeline/pipeline.py --config configs/test_pipeline_config.yaml

echo "------------------------------------------------------------"
echo "Job finished at $(date)"