#!/bin/bash
#SBATCH --job-name=Slice_extraction
#SBATCH --time=2-00:00:00
#SBATCH --partition=gpu
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --output=/home/remote/%u/logs/%x_%j.out
#SBATCH --error=/home/remote/%u/logs/%x_%j.err

# 1. Load the cluster's Conda module
module load miniforge3

# 1. Complete isolation
export PYTHONNOUSERSITE=1
export PYTHONPATH=""

# 2. Force library priority
export LD_LIBRARY_PATH="/home/remote/shghosh/.conda/envs/format/lib:$LD_LIBRARY_PATH"

# 4. Use the full path to your python (as you did before)
/home/remote/shghosh/.conda/envs/format/bin/python /scratch/group/CX000019_DS1/vlm-brain-mri/QA-BrainTumor-VLM-UCSF-/data_pipeline/best_slice_extraction_2d.py
echo "------------------------------------------------------------"
echo "Job finished at $(date)"
