#!/bin/bash
#SBATCH --job-name=MedGemma_finetune
#SBATCH --time=2-00:00:00
#SBATCH --partition=gpu
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err

# Get the absolute path to the project root
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$PROJECT_ROOT" || exit 1

# Ensure logs directory exists
mkdir -p logs

# Dynamic environment detection for MedGemma
ENV_PATH=$(conda env list | grep -E '^vlm-medgemma\s' | awk '{print $NF}')
DYNAMIC_PYTHON="${ENV_PATH}/bin/python"

# 4. Use the full path to your python (as you did before)
"$DYNAMIC_PYTHON" finetune_scripts/model_finetune_3.py
echo "------------------------------------------------------------"
echo "Job finished at $(date)"